'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WorksheetGUI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Banjo_Blinking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Banjo_Blinking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Banjo_Speaking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Banjo_Speaking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property banjo_uh_oh() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("banjo_uh_oh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property banjo1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("banjo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bottles_Blinking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bottles_Blinking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bottles_Speaking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bottles_Speaking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property bottles1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bottles1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property bottles2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bottles2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property bottles3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bottles3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Burp1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Burp1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Burp2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Burp2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Burp3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Burp3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Burp4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Burp4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Captain_Blackeye_Blinking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Captain_Blackeye_Blinking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Captain_Blackeye_Speaking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Captain_Blackeye_Speaking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FloppyDisc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FloppyDisc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property HtmlAgilityPack() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("HtmlAgilityPack", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;doc&gt;
        '''    &lt;assembly&gt;
        '''        &lt;name&gt;HtmlAgilityPack&lt;/name&gt;
        '''    &lt;/assembly&gt;
        '''    &lt;members&gt;
        '''        &lt;member name=&quot;T:HtmlAgilityPack.HtmlAttributeCollection&quot;&gt;
        '''            &lt;summary&gt;
        '''            Represents a combined list and collection of HTML nodes.
        '''            &lt;/summary&gt;
        '''        &lt;/member&gt;
        '''        &lt;member name=&quot;M:HtmlAgilityPack.HtmlAttributeCollection.Add(HtmlAgilityPack.HtmlAttribute)&quot;&gt;
        '''            &lt;summary&gt;
        '''            Adds supplied item to collection
        '''            &lt;/summary&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HtmlAgilityPack1() As String
            Get
                Return ResourceManager.GetString("HtmlAgilityPack1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImperialGuard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImperialGuard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jamjars_Speaking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jamjars_Speaking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property jamjars1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("jamjars1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property jamjars2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("jamjars2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property jamjars3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("jamjars3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property jamjars4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("jamjars4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Kazooie_Blinking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kazooie_Blinking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Kazooie_Speaking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kazooie_Speaking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property kazooie1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kazooie1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property kazooie2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kazooie2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property kazooie3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kazooie3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property kazooie4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kazooie4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Klungo_Blinking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Klungo_Blinking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Klungo_Speaking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Klungo_Speaking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property klungo1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("klungo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property klungo2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("klungo2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property klungo3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("klungo3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mumbo_Blinking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mumbo_Blinking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mumbo_Speaking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mumbo_Speaking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property mumbo1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("mumbo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property mumbo2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("mumbo2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property mumbo3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("mumbo3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property mumbo4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("mumbo4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property mumbo5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("mumbo5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property mumbo6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("mumbo6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Navi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Navi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property OOT_Dialogue_Done_Mono() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OOT_Dialogue_Done_Mono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property OOT_Dialogue_Next() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OOT_Dialogue_Next", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property OOT_PauseMenu_Close_Mono() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OOT_PauseMenu_Close_Mono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property OOT_PauseMenu_Cursor() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OOT_PauseMenu_Cursor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property OOT_PauseMenu_Open_Mono() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OOT_PauseMenu_Open_Mono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property OOT_PauseMenu_Select_Mono() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OOT_PauseMenu_Select_Mono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property OOT_PauseMenu_Turn_Mono() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OOT_PauseMenu_Turn_Mono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Peppy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Peppy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property peppy1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("peppy1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Sabreman_Beep() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Sabreman_Beep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sabreman_Blinking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sabreman_Blinking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sabreman_Speaking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sabreman_Speaking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property StopRightThere() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("StopRightThere", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property StopRightThere_Short() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("StopRightThere_Short", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Tesseract() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Tesseract", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
